server:
  port: 3344

spring:
  application:
    name: microservcecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chengfuse/microservicecloud-config.git #"git@github.com:chengfuse/microservicecloud-config.git"